# Linear Algebra

- Most common linear algebra operation is probably matrix multiplication.

In [1]:
import numpy as np
x = np.ones((2, 3))
x
 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [2]:
y = np.ones((3, 4))
 
y

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

- Note those shapes are different, and not compatible for broadcast.

In [3]:
np.matmul(x, y)

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]])

- Matrix multiplication is so common that there is a special @ overload, so you can write matrix multiplication more concisely with NumPy.

In [4]:
x @ y

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]])

- The second most common is probably the transpose operation that we already saw as a view.

In [5]:
np.transpose(x)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [6]:
x.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

- numpy.dot for dot products. Will be used for dot products, cosine similarity, and linear models.
- numpy.linalg.matrix_rank to check the feasibility of various linear algebra operations
- numpy.linalg.solve to solve linear equations
- numpy.linalg.inv to invert matrices